name: management-stack

networks:
    default:
        name: home-net
        external: true

services:
    dash:
        image: mauricenino/dashdot:latest
        container_name: dash
        privileged: true
        environment:
            DASHDOT_WIDGET_LIST: 'os,cpu,ram,storage,network'
            DASHDOT_ENABLE_CPU_TEMPS: 'true'
            DASHDOT_OVERRIDE_RAM_BRAND: 'G.SKILL Ripjaws V'
            DASHDOT_SHOW_HOST: 'true'
            DASHDOT_CUSTOM_HOST: 'htpc'
            DASHDOT_OS_WIDGET_GROW: '1'
            DASHDOT_STORAGE_WIDGET_ITEMS_PER_PAGE: '5'
            DASHDOT_STORAGE_WIDGET_GROW: '5'
            DASHDOT_NETWORK_WIDGET_GROW: '4'
            DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
            DASHDOT_NETWORK_SPEED_AS_BYTES: 'true'
        volumes:
            - /:/mnt/host:ro
        ports:
            - 3001:3001
        restart: unless-stopped

    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        environment:
            - TZ=${TZ}
            - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./homarr:/appdata
        ports:
            - 7575:7575
        restart: unless-stopped
        
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        environment:
            - TZ=${TZ}
        volumes:
            - ./portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9443:9443
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        environment:
            - LOG_LEVEL=info
            - TZ=${TZ}
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_REMOVE_VOLUMES=true
            - WATCHTOWER_LOG_LEVEL=info
            - WATCHTOWER_POLL_INTERVAL=43200
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped