# Generated by Django 6.0.6 on 2026-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0002_remove_host_add_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='allocated_memory',
            field=models.CharField(db_column='ALLOCATED_MEMORY', default='-', max_length=255, verbose_name='Allocated Memory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='game',
            field=models.CharField(db_column='GAME', max_length=255, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=False, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='notes',
            field=models.TextField(blank=True, db_column='NOTES', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='port',
            field=models.PositiveIntegerField(blank=True, db_column='PORT', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='slug',
            field=models.SlugField(db_column='SLUG', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='version',
            field=models.CharField(blank=True, db_column='VERSION', max_length=255, verbose_name='Version'),
        ),
    ]
