# Generated by Django 6.0.6 on 2026-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0003_add_allocated_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
