# Generated by Django 6.0.6 on 2026-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0004_make_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='container_name',
            field=models.CharField(db_column='CONTAINER_NAME', default='-', max_length=255, verbose_name='Container Name'),
            preserve_default=False,
        ),
    ]
