# Generated by Django 6.0.6 on 2026-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0005_add_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='container_name',
            field=models.CharField(db_column='CONTAINER_NAME', max_length=255, unique=True, verbose_name='Container Name'),
        ),
    ]
