# Generated by Django 6.0.6 on 2026-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0007_alter_allocated_memory_to_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='port',
            field=models.PositiveSmallIntegerField(blank=True, db_column='PORT', null=True, verbose_name='Port'),
        ),
    ]
