# Generated by Django 6.0.6 on 2026-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0008_alter_port_to_small_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='name',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='world_name',
            field=models.CharField(db_column='WORLD_NAME', default='-', max_length=255, unique=True, verbose_name='World Name'),
            preserve_default=False,
        ),
    ]
