name: network-stack

networks:
    macvlan-net:
        name: macvlan-net
        driver: macvlan
        driver_opts:
            parent: ${PARENT_NETWORK_CARD}
            macvlan_mode: bridge
        ipam:
            config:
                - subnet: '${SUBNET}'
                  gateway: '${GATEWAY}'
    media-net:
        external: true

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        hostname: pihole
        networks:
            media-net: {}
            macvlan-net:
                ipv4_address: '${IPV4_ADDRESS}'
        environment:
            TZ: '${TZ}'
            FTLCONF_webserver_api_password: '${WEB_SERVER_PASSWORD}'
            FTLCONF_LOCAL_IPV4: '${IPV4_ADDRESS}'
            FTLCONF_dns_listeningMode: 'all'
        volumes:
            - ./pihole/etc/pihole:/etc/pihole # For persisting Pi-hole's databases and common configuration file
            - ./pihole/etc/dnsmasq.d:/etc/dnsmasq.d
        cap_add:
            - SYS_NICE
        restart: unless-stopped