name: nextcloud-stack

networks:
    default:
        name: home-net
        external: true

x-logging: &default-logging
    driver: json-file
    options:
        max-size: "10m"
        max-file: "3"

services:
    nextcloud-aio-mastercontainer:
        image: ghcr.io/nextcloud-releases/all-in-one:latest
        container_name: nextcloud-aio-mastercontainer
        init: true
        dns:
            - 100.100.100.100  # Tailscale Magic DNS
            - 192.168.6.3      # Pihole DNS
            - 1.1.1.1          # Fallback DNS
        environment:
            APACHE_PORT: ${NEXTCLOUD_BACKEND_HOST_PORT:-9002}
            APACHE_IP_BINDING: 127.0.0.1
            SKIP_DOMAIN_VALIDATION: "true"
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "${NEXTCLOUD_AIO_HOST_PORT:-9001}:8080"
        logging: *default-logging
        restart: unless-stopped

volumes:
    nextcloud_aio_mastercontainer:
        name: nextcloud_aio_mastercontainer
