name: media-stack
    
networks:
    default:
        name: media-net
        external: true

services:
    bazarr: 
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./bazarr:/config
            - ${SHOWS_PATH}:/shows
            - ${ANIME_SERIES_PATH}:/anime-series
            - ${MOVIES_PATH}:/movies
            - ${ANIME_MOVIES_PATH}:/anime-movies
        ports:
            - 6767:6767
        restart: unless-stopped

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=info
            - LOG_HTML=false
            - CAPTCHA_SOLVER=none
            - TZ=${TZ}
        ports:
            - 8191:8191
        restart: unless-stopped

    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./jellyfin:/config
            - ${LIBRARY_PATH}:/library
            - ${TRANSCODES_PATH}:/transcodes
        ports:
            - 8096:8096         # http web ui
            - 7359:7359/udp     # service discovery for clients
        restart: unless-stopped
        
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=${TZ}
            - PORT=5055     
        ports:
            - 5055:5055
        volumes:
            - ./jellyseerr:/app/config
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        restart: unless-stopped

    recyclarr:
        image: ghcr.io/recyclarr/recyclarr
        container_name: recyclarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./recyclarr:/config
        
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped
        
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./radarr:/config
            - ${MOVIES_PATH}:/movies
            - ${ANIME_MOVIES_PATH}:/anime-movies          
            - ${STAGING_PATH}:/staging  
        ports:
            - 7878:7878
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ./sonarr:/config
            - ${SHOWS_PATH}:/shows
            - ${ANIME_SERIES_PATH}:/anime-series
            - ${STAGING_PATH}:/staging  
        ports:
            - 8989:8989
        restart: unless-stopped
