name: frontend-stack
    
networks:
    default:
        name: home-net
        external: true

services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        group_add:
            - ${RENDER_GROUP}
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL}
        volumes:
            - ./jellyfin:/config
            - ${CACHE_PATH}:/cache
            - ${SHOWS_PATH}:/shows
            - ${MOVIES_PATH}:/movies
            - ${ANIME_SERIES_PATH}:/anime_series
            - ${ANIME_MOVIES_PATH}:/anime_movies
        ports:
            - 8096:8096         # http web ui
            - 7359:7359/udp     # service discovery for clients
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        restart: unless-stopped
        
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=${TZ}
            - PORT=5055     
        ports:
            - 5055:5055
        volumes:
            - ./jellyseerr:/app/config
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        restart: unless-stopped
