name: vpn-stack

networks:
    home-net:
        external: true
        
services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        networks:
            - home-net        
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=${TZ}
            - UPDATER_PERIOD=24h
            - VPN_SERVICE_PROVIDER=protonvpn
            - VPN_TYPE=wireguard
            - VPN_PORT_FORWARDING=on
            - PORT_FORWARD_ONLY=on
      
            # ProtonVPN [Interface]
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      
            # Port Mapping
            - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'  
        volumes:
            - ./gluetun:/gluetun
        ports:
            - 8181:8181/tcp # qBittorrent Web UI
        devices:
            - /dev/net/tun:/dev/net/tun  
        restart: unless-stopped
            
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        depends_on:
            gluetun:
                condition: service_healthy
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8181
        volumes:
            - ./qbittorrent/config:/config
            - ${DOWNLOADS_PATH}:/downloads
            - ${INCOMPLETE_DOWNLOADS_PATH}:/incomplete
            - ${TORRENTS_PATH}:/torrents
        restart: unless-stopped
