name: vpn-stack

networks:
    default:
        name: veil
        external: true
        
services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8080:8080/tcp # qBittorrent Web UI
        volumes:
            - ./gluetun:/gluetun
        environment:
            - TZ=${TZ}
            - UPDATER_PERIOD=24h
            - VPN_SERVICE_PROVIDER=protonvpn
            - VPN_TYPE=wireguard
            - VPN_PORT_FORWARDING=on
            - PORT_FORWARD_ONLY=on
      
            # ProtonVPN [Interface]
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      
            # Port Mapping
            - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'            
        restart: unless-stopped
            
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        depends_on:
            gluetun:
                condition: service_healthy
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8080
        volumes:
            - ./qbittorrent/config:/config
            - ${STAGING_PATH}:/staging
        restart: unless-stopped
