# Generated by Django 6.0.6 on 2026-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameserver',
            options={'verbose_name': 'game server', 'verbose_name_plural': 'game servers'},
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='host',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
