# Generated by Django 6.0.6 on 2026-06-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_servers', '0006_make_container_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='allocated_memory',
            field=models.PositiveSmallIntegerField(db_column='ALLOCATED_MEMORY', verbose_name='Allocated Memory (GB)'),
        ),
    ]
