# Generated by Django 6.0.6 on 2026-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsc', '0008_alter_port_to_small_int'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameserver',
            old_name='name',
            new_name='world_name',
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='world_name',
            field=models.CharField(db_column='WORLD_NAME', max_length=255, unique=True, verbose_name='World Name'),
        ),
    ]
