"""Compatibility exports for older PALS callers. New callers use domain services.

Patch dependencies in the module that owns the function, not this facade.
Importing this module does not start the legacy HTTP server or sync saves.
"""

from __future__ import annotations

from .bases import (
    BASE_WORK_CACHE,
    base_coord_text,
    base_work_sites_payload,
    build_base_planner,
    clear_base_work_cache,
    display_owned_location,
    guid_text,
    infer_work_site_skills,
    load_base_labels,
    load_level_world_data,
    planner_auto_target,
    readable_site_name,
    save_base_labels,
    save_to_map_coords,
    work_card_for_owned_row,
)
from .breeding import build_plan, profile_passives_payload
from .breeding_profiles import (
    best_work_speed_profile,
    owned_state_identity,
    restore_profile_tree,
    work_speed_passive_order,
    work_speed_profile_scores,
)
from .breeding_progress import (
    progress_leaf_score,
    progress_notes,
    progress_score,
    progress_sort_key,
    progress_species,
)
from .breeding_search import final_parent_routes, search_states, top_donors_for_species
from .breeding_serialization import (
    build_group,
    cake_recommendation,
    concrete_gender,
    opposite_gender,
    ordered_parent_specs,
    serialize_state,
    unique_serialized,
)
from .breeding_state import (
    State,
    best_storage_substitute,
    compact_states,
    compatible,
    gender_filtered,
    gender_matches,
    iv_sort_bits,
    junk_count,
    owned_location_base_penalty,
    owned_states_for_owner,
    ready_to_finish_states,
    result_sort_key,
    row_to_state,
    state_score,
    substitute_storage_leaves,
    target_complete,
    tree_signature,
    walk_tree,
)
from .data import (
    ANALYZER,
    AUTO_TARGET_CAPS,
    BASE_LABELS_FILE,
    BLUE_PASSIVES,
    BREEDING,
    BreedPal,
    DATA_ROOT,
    DataStore,
    GOLD_PASSIVES,
    IMPLANT_INVENTORY_FILE,
    LEAST_JUNK,
    LIVE_LOCK,
    LIVE_SAVE_DIR,
    LIVE_STATE,
    LIVE_STATE_FILE,
    LOCAL_PAL_IMAGES,
    LOCAL_ROOT,
    NEGATIVE_PASSIVES,
    NORMAL_PASSIVES,
    PALPEDIA_WORK,
    PAL_IMAGES,
    PASSIVE_COLOR_OVERRIDES_FILE,
    PASSIVE_INVENTORY,
    PASSIVE_TONES,
    POPULAR_WORK_PICKS,
    REPORTS_ROOT,
    ROOT,
    ROSTER,
    SIZE_GROUPS,
    SIZE_ORDER,
    SKILL_METADATA,
    STORE,
    TARGET_ONLY,
    TOOLS,
    UPLOADS,
    VALID_PAL_SIZES,
    WEB,
    WORK,
    WORK_LABELS,
    WORK_OVERRIDES,
    WORK_SITE_PATTERNS,
    as_bool,
    as_int,
    base_slot,
    build_passive_meta,
    canonical_passives,
    load_passive_color_overrides,
    match_key,
    normalize_species,
    palbox_position,
    passive_metadata_by_name,
    passive_tone,
    save_passive_color_overrides,
    split_passives,
)
from .ivs import (
    available_implant_passives,
    build_iv_plan,
    improves_selected_iv,
    iv_100_score,
    iv_100_support,
    iv_goal_pair_score,
    iv_goal_score,
    load_implant_inventory,
    owned_target_pals_payload,
    save_implant_inventory,
    serialize_iv_pair,
    serialize_iv_pal,
)
from .legacy_http import Handler, main, start_startup_live_sync
from .ranch import normalized_item_text, ranch_drop_names_for_pal, ranch_drops_payload
from .saves import (
    copy_full_save_to_workspace,
    decode_failure_detail,
    decoder_setup_error,
    empty_dps_json,
    expand_zip_upload,
    live_save_files,
    live_save_fingerprint,
    live_save_status,
    multipart_files,
    persist_live_state,
    refresh_live_save,
    register_refresh_hook,
    reset_directory,
    run_decode_from_level,
    run_decode_from_save_dir,
    run_decode_workspace,
    safe_upload_relative_path,
    save_uploaded_files,
    shortest_file_match,
    wsl_path,
)
from .work import (
    BASE_OPERATION_PASSIVE_PENALTY,
    BASE_OPERATION_PASSIVE_SCORE,
    WORK_ORDER_INDEX,
    WORK_RANK_PASSIVE_PATTERNS,
    WORK_SPEED_PASSIVE_SCORE,
    WORK_SUITABILITY_OVERRIDES,
    WORK_UPTIME_PASSIVE_SCORE,
    actual_owned_work_levels,
    best_owned_work_levels,
    card_final_level,
    condensation_rank_targets,
    fully_condensed_work_levels,
    icon_url_for_key,
    load_work_overrides,
    maximum_owned_work_levels,
    ordered_work_keys,
    owned_species_counts,
    pal_data_for_species,
    pal_image_path,
    pal_size_for,
    palpedia_entry_for,
    passive_work_rank_bonus,
    passive_work_score_parts,
    passive_work_speed_score,
    projected_fully_condensed_work_levels,
    requires_owned_seed_for_breeding,
    species_meta,
    species_types_for_key,
    work_card_for_pal,
    work_entries,
    work_entries_from_levels,
    work_for_pal,
    work_override_for,
    work_recommendations,
    work_source_for,
    work_suitability_payload,
)


if __name__ == "__main__":
    main()
