name: firefly-stack

networks:
    home-net:
        external: true
    firefly-net:
        driver: bridge

services:
    app:
        image: fireflyiii/core:latest
        hostname: app
        container_name: firefly_iii_core
        networks:
        - firefly-net
        - home-net
        depends_on:
        - db
        env_file: .env
        volumes:
        - ./firefly_iii_upload:/var/www/html/storage/upload
        ports:
        - 8081:8080
        restart: unless-stopped
    cron:
        image: alpine
        container_name: firefly_iii_cron
        networks:
        - firefly-net
        - home-net
        depends_on:
        - app
        env_file: .env
        command: sh -c "apk add tzdata && ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime && echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\" | crontab - && crond -f -L /dev/stdout"
        restart: unless-stopped
    db:
        image: mariadb:lts
        hostname: db
        container_name: firefly_iii_db
        env_file: .db.env
        networks:
        - firefly-net
        - home-net 
        volumes:
        - ./firefly_iii_db:/var/lib/mysql
        restart: unless-stopped
    importer:
        image: fireflyiii/data-importer:latest
        hostname: importer
        container_name: firefly_iii_importer
        networks:
        - firefly-net
        - home-net
        depends_on:
        - app
        env_file: .importer.env
        ports:
        - 8082:8080
        restart: unless-stopped