name: utilities-stack

networks:
    default:
        name: home-net
        external: true

services:
    bentopdf:
        image: bentopdf/bentopdf:latest
        container_name: bentopdf
        volumes:
            - ./bentopdf:/data
        ports:
            - ${BENTOPDF_PORT:-3001}:8080
        restart: unless-stopped

    omni-tools:
        image: iib0011/omni-tools:latest
        container_name: omni-tools
        volumes:
            - ./omni-tools:/data
        ports:
            - ${OMNI_TOOLS_PORT:-3002}:80
        restart: unless-stopped

    paperless-ai:
        image: clusterzx/paperless-ai:latest
        container_name: paperless-ai
        environment:
            RAG_SERVICE_URL: http://webserver:8000
            RAG_SERVICE_ENABLED: true
            PUID: ${PUID}
            PGID: ${PGID}
            PAPERLESS_TIME_ZONE: ${TZ}
        volumes:
            - ./paperless-ai:/app/data
        ports:
            - ${PAPERLESS_AI_PORT:-3003}:3000
        restart: unless-stopped

    broker:
        image: docker.io/library/redis:8
        container_name: paperless-broker
        volumes:
            - ./paperless-ngx/data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 5s
            retries: 5
        restart: unless-stopped
    db:
        image: docker.io/library/postgres:18
        container_name: paperless-db
        volumes:
            - ./paperless-ngx/postgresql:/var/lib/postgresql
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 30s
            timeout: 5s
            retries: 5
        restart: unless-stopped
    webserver:
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        container_name: paperless-webserver
        depends_on:
            db:
                condition: service_healthy
            broker:
                condition: service_healthy
        ports:
            - ${PAPERLESS_WEB_PORT:-3004}:8000
        volumes:
            - ./paperless-web/data:/usr/src/paperless/data
            - ./paperless-web/media:/usr/src/paperless/media
            - ./paperless-web/export:/usr/src/paperless/export
            - ./paperless-web/consume:/usr/src/paperless/consume
        environment:
            PAPERLESS_REDIS: redis://broker:6379
            PAPERLESS_DBHOST: db
            PAPERLESS_TIME_ZONE: ${TZ}
            PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE:-eng}
            PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES:-eng}
        restart: unless-stopped
