name: utilities-stack

networks:
    default:
        name: home-net
        external: true

services:
    bentopdf:
        image: bentopdf/bentopdf:latest
        container_name: bentopdf
        volumes:
            - ./bentopdf:/data
        ports:
            - 3000:8080
        restart: unless-stopped

    omni-tools:
        image: iib0011/omni-tools:latest
        container_name: omni-tools
        volumes:
            - ./omni-tools:/data
        ports:
            - 8085:80
        restart: unless-stopped

    paperless-ai:
        image: clusterzx/paperless-ai:latest
        container_name: paperless-ai
        volumes:
            - ./paperless-ai:/app/data
        ports:
            - 3001:3000
        restart: unless-stopped

    broker:
        image: docker.io/library/redis:8
        container_name: paperless-broker
        volumes:
            - ./paperless-ngx/redisdata:/data
        restart: unless-stopped
    db:
        image: docker.io/library/postgres:18
        container_name: paperless-db
        volumes:
            - ./paperless-ngx/pgdata:/var/lib/postgresql
        environment:
            POSTGRES_DB: paperless
            POSTGRES_USER: paperless
            POSTGRES_PASSWORD: paperless
        restart: unless-stopped
    webserver:
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        container_name: paperless-webserver
        depends_on:
            - db
            - broker
        ports:
            - "8000:8000"
        volumes:
            - ./paperless-ngx/data:/usr/src/paperless/data
            - ./paperless-ngx/media:/usr/src/paperless/media
            - ./paperless-ngx/export:/usr/src/paperless/export
            - ./paperless-ngx/consume:/usr/src/paperless/consume
        env_file: docker-compose.env
        environment:
            PAPERLESS_REDIS: redis://broker:6379
            PAPERLESS_DBHOST: db
        restart: unless-stopped
