name: cloud-stack

networks:
    default:
        name: home-net
        external: true

x-logging: &default-logging
    driver: json-file
    options:
        max-size: "10m"
        max-file: "3"

services:

    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - ./filebrowser/srv:/srv
            - ./filebrowser/database:/database
            - ./filebrowser/config:/config
        ports:
            - "${FILEBROWSER_HOST_PORT:-9001}:80"
        logging: *default-logging
        restart: unless-stopped

    syncthing:
        image: lscr.io/linuxserver/syncthing:latest
        container_name: syncthing
        hostname: syncthing 
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - ./syncthing/config:/config
            - ./syncthing/data1:/data1
            - ./syncthing/data2:/data2
        ports:
            - "${SYNCTHING_HOST_PORT:-9002}:8384"
            - "${SYNCTHING_TCP_HOST_PORT:-9003}:22000/tcp"
            - "${SYNCTHING_UDP_HOST_PORT:-9003}:22000/udp"
            - "${SYNCTHING_DISCOVERY_HOST_PORT:-9004}:21027/udp"
        logging: *default-logging
        restart: unless-stopped
